### ISSUE TITLE
Make irssi_ssl_get_iochannel accessible for plugins

### ISSUE THREAD

**Issue by phhusson** [irssi/irssi#615]
The Quassel protocol doesn't start straight as TLS, but has a protocol-negociation before-hand.
Hence, quassel-irssi can't just use standard use_tls=1 of irssi (unless I've missed something, in which case, please tell!)

At the moment, to handle this, quassel-irssi has a copy/paste of irssi's network-openssl.c, which is obviously ugly, and isn't update-proof (it has been broken by irssi 1.0.0)

Would it be possible to make this symbol public?

**Comment by ailin-nemui** [comment]
hi, can you discuss if there are any issues that require you to poll here https://github.com/phhusson/quassel-irssi/blob/master/core/quassel-net.c#L171

**Comment by ailin-nemui** [comment]
please check if this would work

**Comment by phhusson** [comment]
Yup, that function is perfect.
For the polling part, it was mostly lazyness, I've now implemented it properly (I think):
https://github.com/phhusson/quassel-irssi/commit/19e810405789a35b92026b56ea49d01a3f544b07

quassel_net_ssl_callback is partly a copy/paste of server_connect_callback_init_ssl.
This isn't really a problem I think, though this is a possible improvement.

**Comment by ailin-nemui** [comment]
cool thanks for the feedback.

**Comment by ailin-nemui** [comment]
@phhusson from what I can tell you're still having the polling code in line 219 there
